class ActionEnum:

    PING = "PING"
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    SELECT = "SELECT"

    CREATE_TABLE = "CREATE_TABLE"

    DROP_TABLE = "DROP_TABLE"

    LOGIN = "LOGIN"

    ERROR = "ERROR"
